server:
  host: 0.0.0.0
  port: 9758

login:
  username: user
  password: youshallnotpass

  token: no-token.4.u

logging:
  log_level: DEBUG
  project_name: website

figlet:
  start: PiStat
  stop: Goodbye
  
  width: 80
  font: standard
 
version:
  major: 1
  minor: 0
  patch: 0
  release: stable